### ISSUE TITLE
Wire in Firebase Auth

### ISSUE THREAD

**Issue by eeeeeric** [warlocks-of-the-midwest/mystic-get-together#15]
I published [my life counter sample app](https://github.com/eeeeeric/life-counter-for-mtg) just now. It should serve as a good example on how to wire in Firebase Auth. The sample app is written using VueJS (and other components in the Vue ecosystem like vue-router and vuex).

The key things to do are:
* Add `firebase` and `firebaseui` dependencies
* Port [these changes](https://github.com/eeeeeric/life-counter-for-mtg/commit/3d47cb5317a0267c4e04cd698e796a753e93258e#diff-17803ee410d08d15bd5892bf6519f40a) which are the most important - it starts up the auth ui (this is a component provided by the `firebaseui` library and does all the hard work for you
* Port [these other changes](https://github.com/eeeeeric/life-counter-for-mtg/commit/3d47cb5317a0267c4e04cd698e796a753e93258e#diff-8cfead41d88ad47d44509a8ab0a109ad) which let you know when the auth state has changed (so you could perhaps persist the profile information somewhere)
* Store the user's profile information somewhere (I stored it using vuex - you might use redux) - you could also use a cookie
* Once you are authenticated, you don't really need to do anything. Calls to firebase using the firebase SDK will automatically include your auth token

**Comment by eeeeeric** [comment]
Updated original post to include another set of important changes to port and re-ordered an item so it makes more sense.

**Comment by eeeeeric** [comment]
Also thank you @acmorales for taking this.

**Comment by acmorales** [comment]
Wired in. Gonna do a little UI work with this issue and will open a PR
