### ISSUE TITLE
Update redux for the new Firebase schema

### ISSUE THREAD

**Issue by eeeeeric** [warlocks-of-the-midwest/mystic-get-together#18]
Pending resolution of #16 and #17 

The scope of this issue is to update the reducer that handles new Firebase data.

[This](https://github.com/eeeeeric/life-counter-for-mtg/blob/master/src/store.ts#L69) vuex mutation (the equivalent of a redux reducer) handles the updates from the SDK. Notable is how we can differentiate between write types (create, update, delete). Also of note is that when you first get a snapshot from the listener, it will contain add changes for _all existing_ docs, meaning nothing special has to be done to initialize the store with the initial set of data.

Since the data is now coming in on a per card basis, the reducer has more freedom on how to structure the data in redux.

**Comment by eeeeeric** [comment]
I think #42 resolves this, or at least, partially resolves this. I'm going to include this in next week's milestone and also assign Henry. You guys can figure out when this is actually resolved.

**Comment by acmorales** [comment]
UI has been updated for the new schema in #39 so once we get both in, this can be resolved
