### ISSUE TITLE
Add lifecycle status property to games

### ISSUE THREAD

**Issue by acmorales** [warlocks-of-the-midwest/mystic-get-together#73]
It'd be pretty nice for menus if games had a lifecycle status, e.g., LOBBY (created but not started), IN_PROGRESS, and ENDED. Also games in the ENDED state should be cleaned up automatically somehow, maybe by a function running a cron job.

**Comment by eeeeeric** [comment]
We might want to make some info like X players in lobby in the root game document too. Since this adds an in progress indicator, this should make it easier to implement #41. I'm still not sure how we can guarantee that a game is ENDED eventually.

**Comment by eeeeeric** [comment]
I opened #82 for the clean up portion of this.

**Comment by eeeeeric** [comment]
We will still need a way to manually mark a game as ended.
